export const DEMO_TABAN1_MOVIES = [
  {
    id: 9901,
    title: 'تۆپی پێ - کورتەی یارییە بەناوبانگەکان',
    title_ku: 'تۆپی پێ - کورتەی یارییە بەناوبانگەکان',
    title_ar: 'ملخصات كروية حماسية',
    year: '2026',
    rating: '9.8',
    type: 'Movie',
    genre: 'وەرزشی',
    list_name: 'ڤیدیۆی وەرزشی',
    category: 'ڤیدیۆی وەرزشی',
    image: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=800&auto=format&fit=crop&q=80',
    backdrop: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=1200&auto=format&fit=crop&q=80',
    description: 'خۆشترین و بەهێزترین کورتەی یارییەکانی تۆپی پێ بە کوالیتی بەرزی HD.',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4'
  },
  {
    id: 9902,
    title: 'خۆشترین گۆڵەکانی جیهان 2026',
    title_ku: 'خۆشترین گۆڵەکانی جیهان 2026',
    title_ar: 'أجمل أهداف العالم 2026',
    year: '2026',
    rating: '9.6',
    type: 'Movie',
    genre: 'وەرزشی',
    list_name: 'ڤیدیۆی وەرزشی',
    category: 'ڤیدیۆی وەرزشی',
    image: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800&auto=format&fit=crop&q=80',
    backdrop: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=1200&auto=format&fit=crop&q=80',
    description: 'کۆکراوەی سەرنجڕاکێشترین گۆڵە مێژووییەکانی یاریزانە ناودارەکان.',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4'
  },
  {
    id: 9903,
    title: 'یاریگای پڕ لە هیجان - ڕووداوە وەرزشییەکان',
    title_ku: 'یاریگای پڕ لە هیجان - ڕووداوە وەرزشییەکان',
    title_ar: 'إثارة الملاعب الرياضية',
    year: '2025',
    rating: '9.4',
    type: 'Movie',
    genre: 'وەرزشی',
    list_name: 'ڤیدیۆی وەرزشی',
    category: 'ڤیدیۆی وەرزشی',
    image: 'https://images.unsplash.com/photo-1518091043644-c1d4457512c6?w=800&auto=format&fit=crop&q=80',
    backdrop: 'https://images.unsplash.com/photo-1518091043644-c1d4457512c6?w=1200&auto=format&fit=crop&q=80',
    description: 'دیارترین ساتە وەرزشییەکان لە جیهانی ڕاکردن و سەرمەشقی وەرزشی.',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4'
  },
  {
    id: 9904,
    title: 'مۆمێنتی کۆمیدی و پێکەنیناوی 2026',
    title_ku: 'مۆمێنتی کۆمیدی و پێکەنیناوی 2026',
    title_ar: 'أقوى اللقطات المضحكة 2026',
    year: '2026',
    rating: '9.7',
    type: 'Movie',
    genre: 'کۆمیدی',
    list_name: 'کۆمیدی و پێکەنین',
    category: 'کۆمیدی و پێکەنین',
    image: 'https://images.unsplash.com/photo-1514306191717-452ec28c7814?w=800&auto=format&fit=crop&q=80',
    backdrop: 'https://images.unsplash.com/photo-1514306191717-452ec28c7814?w=1200&auto=format&fit=crop&q=80',
    description: 'کۆمەڵێک ساتی کۆمیدی زۆر بەزم و پێکەنیناوی جیهانی.',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4'
  },
  {
    id: 9905,
    title: 'بەزمی پێکەنین و ئەکتەرە کۆمیدییەکان',
    title_ku: 'بەزمی پێکەنین و ئەکتەرە کۆمیدییەکان',
    title_ar: 'ضحك وبث كوميدي ساخر',
    year: '2025',
    rating: '9.5',
    type: 'Movie',
    genre: 'کۆمیدی',
    list_name: 'کۆمیدی و پێکەنین',
    category: 'کۆمیدی و پێکەنین',
    image: 'https://images.unsplash.com/photo-1585699324551-f6c309eedeca?w=800&auto=format&fit=crop&q=80',
    backdrop: 'https://images.unsplash.com/photo-1585699324551-f6c309eedeca?w=1200&auto=format&fit=crop&q=80',
    description: 'شۆ و نمایشی کۆمیدی تایبەت بۆ بەسەربردنی کاتێکی خۆش.',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4'
  }
];
